### ISSUE TITLE
IPOP wget on centOS

### ISSUE THREAD

**Issue by apsankar** [ipop-project/Release-Management#5]
Hi. So the automated installation for IPOP involves downloading the corresponding tar ball for that distribution, unpacking it, and also downloading an 'ipop' installation script and an installer.stat file.

In centOS though, when we 'wget' the link, only the 'ipop' installation script and the installer.stat file are downloaded; the tar ball is not. Trying to do a "./ipop install" doesn't help either. No error messages are printed when we try to install or start, so a potential new user could be confused.

**Comment by vdaneshmand** [comment]
Hi Aswin;

Thanks a lot for the bug report. Have you run this command?

`wget -O - http://raw.githubusercontent.com/ipop-project/Release-Management/master/Deployment/linux/installer | /bin/bash`

- Vahid

**Comment by apsankar** [comment]
Hi Vahid,

Just an update, running this command (master instead of v16.01.0) doesn't help either; the ipop-centOS tar ball isn't being downloaded.

**Comment by vdaneshmand** [comment]
@apsankar, Fixed. :-)
